// export const curatedFewShotTokenCache = {
//   system_configuration: [
//     'server',
//     'uptime',
//     'health',
//     'monitor',
//     'logs',
//     'errors',
//     'database',
//     'infrastructure',
//     'cpu',
//     'memory',
//     'latency',
//     'backup',
//     'metrics',
//     'scaling',
//     'gateway',
//     'deployment',
//     'cicd',
//     'network',
//     'bandwidth',
//     'cache',
//     'redis',
//     'disk',
//     'replication',
//     'pipeline',
//     'config',
//   ],

//   data_analysis: [
//     'overview',
//     'analysis',
//     'analyze',
//     'statistics',
//     'average',
//     'median',
//     'distribution',
//     'trend',
//     'outliers',
//     'correlation',
//     'dashboard',
//     'report',
//     'percentile',
//     'variance',
//     'standard',
//     'deviation',
//     'cohort',
//     'performance',
//     'scores',
//     'grades',
//     'passrate',
//     'completion',
//     'class',
//     'student',
//     'students',
//     'analytics',
//     'results',
//     'progress',
//     'insights',
//   ],

//   quiz_creation: [
//     'quiz',
//     'questions',
//     'assessment',
//     'test',
//     'practice',
//     'exercises',
//     'multiple',
//     'choice',
//     'distractors',
//     'rubrics',
//     'midterm',
//     'final',
//     'shortanswer',
//     'conceptual',
//     'application',
//     'review',
//     'chapter',
//     'unit',
//     'biology',
//     'calculus',
//     'probability',
//     'physics',
//     'chemistry',
//     'algebra',
//   ],
// };

// Few-shot examples: provide example texts for each category
export const fewShotExamples = {
  system_configuration: [
    // 'Check overall system health status.',
    // 'Is the platform healthy right now?',
    // 'Give me a quick health check for the service.',
    // 'Check if the application is up and stable.',
    // 'Show current uptime and basic health summary.',
    // 'Verify that core services are running normally.',
    // 'Run a general health check for the LMS.',
    'Is everything operating normally in the system?',
    'Check recent logs for errors and warnings.',
    'Show the latest system logs with limit 20 and offset 0.',
    'Retrieve logs from userId usr_001 with limit 10 and offset 0.',
    'Get log entries related to login failures in the last day.',
    'Check logs for timeout events and summarize them.',
    'Pull audit logs for admin actions with pagination.',
    'Retrieve logs by userId usr_042 and show recent entries.',
    'Get warning and error logs with limit 50 and offset 0.',
    'Analyze logs and highlight recurring issues.',
    'Check system logs and tell me if there are any critical issues.',
    'Review the latest logs and identify potential problems.',
    'Scan recent logs for abnormal errors and suspicious patterns.',
    'Inspect application logs and report anything that looks wrong.',
    'Check error logs and summarize the main issues we should fix first.',
    'Check course enrollments with status Pending and limit 30 offset 0.',
    'Check course enrollments with status Completed and limit 30 offset 0.',
    'Retrieve course enrollments with status Unregistered and summarize.',
    'Analyze enrollment trends for courses this semester.',
    'Show enrollments from 2025-01-01 to 2025-12-31 with status Completed.',
    'Compare enrollment counts by status across all courses.',
    'Summarize pending enrollments that require admin action.',
    'Analyze course enrollment logs and report anomalies.',
  ],

  data_analysis: [
    // --- Overview & General ---
    'Give me an overview of quiz results',
    'Analyze the scores from class L01',
    'Show me statistics about student performance in this course',
    'What are the average grades?',
    'Generate a report on quiz results',
    'Compare performance across different classes',
    'What percentage of students passed the exam?',
    'Show me the grade distribution for this course',

    // --- Trend Analysis (MỚI CẬP NHẬT) ---
    'Show me the completion trend of quiz001 over the last few months.',
    'Is the number of submissions increasing or decreasing?',
    'Analyze the quiz completion rate for class001 this semester',
    'How active are the students in class001 lately?',
    'Show the monthly submission statistics for quiz001',
    'Compare the completion trend between January and March',
    'Analyze the improvement trend over time',
    'Calculate average improvement rates per student cohort',

    // --- Risk & Performance ---
    'Identify students who are struggling and need intervention',
    'Identify weak students in class001',
    'Who are the top performers and at-risk students?',
    'Flag any outliers and list students who dropped more than 10 points',
    'Evaluate student scores and identify alarming results',

    // --- Knowledge Gap ---
    'Analyze which topics students struggled with most',
    'What are the common misconceptions for quiz001?',
    'Show the skill matrix and mastery levels for this class',
    'Identify the knowledge gaps in the recent assessment',
    'Which questions had the most wrong answers?',

    // --- Stats ---
    'Calculate the median score for the assignment',
    'Show the grade trends over the past three months',
    'Generate a correlation analysis between quiz and exam scores',
    'Calculate the standard deviation and percentile ranks',
    'Analyze attendance patterns and their impact on performance',
  ],

  quiz_creation: [
    'Create a quiz about mathematics',
    'Generate assessment questions for chapter 5',
    'Design a test for chapter 3',
    'Make practice questions about photosynthesis',
    'Design practice problems for calculus',
    'Create exercises for linear algebra',
    'Generate practice problems for students',
    'Make a test about chemistry',
    'Build assessment questions for physics',
    'Make a test about history of Vietnam',
    'Design a new assessment pack for our biology unit',
    'Create a quiz on cell division and genetics',
    'Add short-answer questions about DNA replication',
    'Give me higher-order questions that assess critical thinking rather than memorization',
    'Create a 20-question quiz on probability basics',
    'Add practice problems about conditional probability and Bayes theorem',
    'Build a mini-test for statistics covering mean, variance, and standard deviation',
    'Include an answer key for each part',
    'Generate multiple-choice questions with distractors',
    'Create a comprehensive exam with rubrics',
    'Design formative assessment questions for the midterm',
    'Build a quiz package covering limits, derivatives, and integrals',
    'Create application problems about optimization',
    'Generate conceptual questions that test intuition rather than computation',
    'Make practice exercises for the review session',
  ],
};

export const curatedFewShotTokenCache = {
  system_configuration: [
    'server',
    'uptime',
    'health',
    'monitor',
    'logs',
    'errors',
    'database',
    'infrastructure',
    'cpu',
    'memory',
    'latency',
    'backup',
    'metrics',
    'scaling',
    'gateway',
    'deployment',
    'cicd',
    'network',
    'bandwidth',
    'cache',
    'redis',
    'disk',
    'replication',
    'pipeline',
    'config',
    'log',
    'userid',
    'limit',
    'offset',
    'course',
    'enrollment',
    'enrollments',
    'pending',
    'completed',
    'unregistered',
  ],

  data_analysis: [
    'overview',
    'analysis',
    'analyze',
    'statistics',
    'average',
    'median',
    'distribution',
    'trend',
    'outliers',
    'correlation',
    'dashboard',
    'report',
    'percentile',
    'variance',
    'standard',
    'deviation',
    'cohort',
    'performance',
    'scores',
    'grades',
    'passrate',
    'completion',
    'class',
    'student',
    'students',
    'analytics',
    'results',
    'progress',
    'insights',
    'misconception',
    'gap',
    'struggling',
    'risk',
    'top',
    'bottom',
  ],

  quiz_creation: [
    'quiz',
    'questions',
    'assessment',
    'test',
    'practice',
    'exercises',
    'multiple',
    'choice',
    'distractors',
    'rubrics',
    'midterm',
    'final',
    'shortanswer',
    'conceptual',
    'application',
    'review',
    'chapter',
    'unit',
    'biology',
    'calculus',
    'probability',
    'physics',
    'chemistry',
    'algebra',
  ],
};
